language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
services:
  - postgresql
before_script:
  - pip install --user codecov
  - npm install
  - psql -c 'create database test;' -U postgres
script:
  - npm run test
after_success:
  - codecov --file coverage/lcov.info --disable search
notifications:
  email: false
